### ISSUE TITLE
Onlyoffice can support dropdown selection and macros？

### ISSUE THREAD

**Issue by hanitao** [ONLYOFFICE/CommunityServer#178] opened 2019-10-08 03:16 UTC
Onlyoffice can support dropdown selection and macros？

**Comment by ShockwaveNN** [comment] 2019-10-08 08:22
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/252
and https://github.com/ONLYOFFICE/DocumentServer/issues/240

**Closed by ShockwaveNN** 2019-10-08 08:22 UTC
