### ISSUE TITLE
Are AGPL and CLA compatible? What about GDPR too?

### ISSUE THREAD

**Issue by Thatoo** [ONLYOFFICE/CommunityServer#476] opened 2023-07-04 16:00 UTC
I wrote some thought about it in here : https://github.com/ONLYOFFICE/DocumentServer/issues/2288

**Comment by catbasilio** [comment] 2023-08-14 13:46
Close as duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/2288

**Closed by catbasilio** 2023-08-14 13:46 UTC
Labels: duplicate
