### ISSUE TITLE
full-text search on Chinese document don't work

### ISSUE THREAD

**Issue by gaord** [ONLYOFFICE/CommunityServer#449] opened 2023-01-06 13:06 UTC
Hi, I am running onlyoffice workspace 12.1.0. there already uploaded quite some Chinese documents. When I search Chinese text as below. I got nothing returned. I am sure there is occurrences in documents. When searching English, it works ok.

![image](https://user-images.githubusercontent.com/9567937/211016896-61661c57-8cb4-46b0-baf3-c330477f36b1.png)

After some investigation, it turns out that there need to install ik analyzer plugin in elastic search container to make it work with Chinese text searching. I have installed the plugin. However, Communityserver just uses whitespace analyzer (ES build-in one) all the way. Could I make configuration to have Communityserver  use the installed analyzer in making index and searching text? Thank you.

**Comment by Carazyda** [comment] 2023-01-06 13:53
Hello @gaord this is a duplicate of https://github.com/ONLYOFFICE/CommunityServer/issues/271. Search in Chinese only works with a complete match. Unfortunately, I can't help you with setting up the plugins for the ES. Let's leave the issue open, maybe someone from the community can help you.

**Comment by gaord** [comment] 2023-01-06 22:18
What a pity, given that we have accumulated quite huge number of documents in English, Chinese or maybe other languages. Searching with document content adaptively is a must-have. Similar issues have been around community for quite some time. I wonder if there is a plan to address it or not. What's policy for PR from community? Thanks. @Carazyda

**Comment by gaord** [comment] 2023-01-11 10:04
It looks like to get it work by putting updated index settings to ES. Hacking way. Hope it could be addressed by configuration in near future.

**Comment by Carazyda** [comment] 2023-01-11 11:07
We will fix this in the next versions. Close this issue as duplicate of #271.

**Closed by Carazyda** 2023-01-11 11:07 UTC
