### ISSUE TITLE
Docker-compose up =>  [ERROR] Could not open file '/var/log/mysql/error.log' for error logging: No such file or directory

### ISSUE THREAD

**Issue by molekm** [ONLYOFFICE/CommunityServer#412] opened 2022-08-04 22:18 UTC
Tried to re-install Ubuntu 18.04, used most recent Docker using OnlyOffice links & documentation.

Old version of OnlyOffice (8 months old ?) was working fine.

`onlyoffice-mysql-server        | 2022-08-04 22:16:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.39-1.el7 started.
onlyoffice-mysql-server        | 2022-08-04 22:16:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
onlyoffice-mysql-server        | 2022-08-04 22:16:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.39-1.el7 started.
onlyoffice-mysql-server        | 2022-08-04 22:16:10+00:00 [Note] [Entrypoint]: Initializing database files
onlyoffice-mysql-server        | 2022-08-04T22:16:10.757172Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
onlyoffice-mysql-server        | 2022-08-04T22:16:10.757234Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
onlyoffice-mysql-server        | 2022-08-04T22:16:10.759400Z 0 [ERROR] Could not open file '/var/log/mysql/error.log' for error logging: No such file or directory
onlyoffice-mysql-server        | 2022-08-04T22:16:10.759436Z 0 [ERROR] Aborting
`

**Comment by Carazyda** [comment] 2022-08-05 13:26
Hello @molekm this is duplicate of https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/161

**Closed by Carazyda** 2022-08-05 13:26 UTC
