### ISSUE TITLE
How to create a Debian package

### ISSUE THREAD

**Issue by collab-smart** [ONLYOFFICE/CommunityServer#492] opened 2023-12-21 20:06 UTC
Hi @alexeybannov Good day!

Could you please help me how to make a Debian package of community server after compilation?

**Comment by Carazyda** [comment] 2023-12-25 06:27
Duplicate of https://github.com/ONLYOFFICE/CommunityServer/issues/491

**Closed by Carazyda** 2023-12-25 06:27 UTC
