### ISSUE TITLE
Community server Folder sharing

### ISSUE THREAD

**Issue by xunmeng2015** [ONLYOFFICE/CommunityServer#280] opened 2021-03-15 05:03 UTC
For folder a. 
Group A access by 1(read and write), group B access by 2(read only), all user in group A is also in group B. However, after i set this configuration, all user in group A's access by 2(read only). What can i do?

**Comment by ShockwaveNN** [comment] 2021-03-15 05:53
Duplicate of https://github.com/ONLYOFFICE/CommunityServer/issues/279

**Closed by ShockwaveNN** 2021-03-15 05:53 UTC
